import os

js_code = (
    '/**\n'
    ' * FastApiOCRService - Bridge between Node.js and FastAPI ai-service\n'
    ' */\n'
    '\n'
    'const fs = require("fs");\n'
    'const path = require("path");\n'
    'const http = require("http");\n'
    'const https = require("https");\n'
    'const FormData = require("form-data");\n'
    '\n'
    'const AI_SERVICE_URL = process.env.AI_SERVICE_URL || "http://localhost:8000";\n'
    'const FASTAPI_TIMEOUT_MS = 5000;\n'
    '\n'
    'async function callFastApiOCR(filePath, rawText, fileName, documentType) {\n'
    '  return new Promise(function(resolve, reject) {\n'
    '    const form = new FormData();\n'
    '    if (filePath && fs.existsSync(filePath)) {\n'
    '      form.append("file", fs.createReadStream(filePath), {\n'
    '        filename: path.basename(filePath),\n'
    '        contentType: "application/octet-stream"\n'
    '      });\n'
    '      form.append("fileName", path.basename(filePath));\n'
    '    } else if (rawText) {\n'
    '      form.append("rawText", rawText);\n'
    '    } else {\n'
    '      return reject(new Error("No file or rawText provided"));\n'
    '    }\n'
    '    if (fileName) form.append("fileName", fileName);\n'
    '    if (documentType) form.append("documentType", documentType);\n'
    '    const urlObj = new URL(AI_SERVICE_URL + "/ocr");\n'
    '    const isHttps = urlObj.protocol === "https:";\n'
    '    const transport = isHttps ? https : http;\n'
    '    const port = urlObj.port || (isHttps ? 443 : 80);\n'
    '    const options = {\n'
    '      hostname: urlObj.hostname,\n'
    '      port: port,\n'
    '      path: urlObj.pathname,\n'
    '      method: "POST",\n'
    '      headers: form.getHeaders(),\n'
    '      timeout: FASTAPI_TIMEOUT_MS\n'
    '    };\n'
    '    const req = transport.request(options, function(res) {\n'
    '      let data = "";\n'
    '      res.on("data", function(chunk) { data += chunk; });\n'
    '      res.on("end", function() {\n'
    '        try {\n'
    '          const parsed = JSON.parse(data);\n'
    '          if (res.statusCode >= 200 && res.statusCode < 300) {\n'
    '            resolve(parsed);\n'
    '          } else {\n'
    '            reject(new Error("FastAPI returned " + res.statusCode + ": " + data));\n'
    '          }\n'
    '        } catch (e) {\n'
    '          reject(new Error("FastAPI JSON parse error: " + e.message));\n'
    '        }\n'
    '      });\n'
    '    });\n'
    '    req.on("timeout", function() {\n'
    '      req.destroy(new Error("FastAPI /ocr timed out after " + FASTAPI_TIMEOUT_MS + "ms"));\n'
    '    });\n'
    '    req.on("error", function(err) { reject(err); });\n'
    '    form.pipe(req);\n'
    '  });\n'
    '}\n'
    '\n'
    'async function callFastApiExtractDates(rawText, documentType) {\n'
    '  return new Promise(function(resolve, reject) {\n'
    '    const body = JSON.stringify({ rawText: rawText, documentType: documentType || null });\n'
    '    const urlObj = new URL(AI_SERVICE_URL + "/extract-dates");\n'
    '    const isHttps = urlObj.protocol === "https:";\n'
    '    const transport = isHttps ? https : http;\n'
    '    const port = urlObj.port || (isHttps ? 443 : 80);\n'
    '    const options = {\n'
    '      hostname: urlObj.hostname,\n'
    '      port: port,\n'
    '      path: urlObj.pathname,\n'
    '      method: "POST",\n'
    '      headers: {\n'
    '        "Content-Type": "application/json",\n'
    '        "Content-Length": Buffer.byteLength(body)\n'
    '      },\n'
    '      timeout: FASTAPI_TIMEOUT_MS\n'
    '    };\n'
    '    const req = transport.request(options, function(res) {\n'
    '      let data = "";\n'
    '      res.on("data", function(chunk) { data += chunk; });\n'
    '      res.on("end", function() {\n'
    '        try {\n'
    '          const parsed = JSON.parse(data);\n'
    '          if (res.statusCode >= 200 && res.statusCode < 300) {\n'
    '            resolve(parsed);\n'
    '          } else {\n'
    '            reject(new Error("FastAPI /extract-dates returned " + res.statusCode));\n'
    '          }\n'
    '        } catch (e) {\n'
    '          reject(new Error("FastAPI /extract-dates JSON parse error: " + e.message));\n'
    '        }\n'
    '      });\n'
    '    });\n'
    '    req.on("timeout", function() {\n'
    '      req.destroy(new Error("FastAPI /extract-dates timed out after " + FASTAPI_TIMEOUT_MS + "ms"));\n'
    '    });\n'
    '    req.on("error", function(err) { reject(err); });\n'
    '    req.write(body);\n'
    '    req.end();\n'
    '  });\n'
    '}\n'
    '\n'
    'let _fastApiAvailable = null;\n'
    'let _fastApiLastCheck = 0;\n'
    'const FASTAPI_CACHE_TTL = 30000;\n'
    '\n'
    'async function isFastApiAvailable() {\n'
    '  const now = Date.now();\n'
    '  if (_fastApiAvailable !== null && now - _fastApiLastCheck < FASTAPI_CACHE_TTL) return _fastApiAvailable;\n'
    '  return new Promise(function(resolve) {\n'
    '    const urlObj = new URL(AI_SERVICE_URL + "/health");\n'
    '    const isHttps = urlObj.protocol === "https:";\n'
    '    const transport = isHttps ? https : http;\n'
    '    const port = urlObj.port || (isHttps ? 443 : 80);\n'
    '    const req = transport.request({\n'
    '      hostname: urlObj.hostname,\n'
    '      port: port,\n'
    '      path: urlObj.pathname,\n'
    '      method: "GET",\n'
    '      timeout: 2000\n'
    '    }, function(res) {\n'
    '      _fastApiAvailable = res.statusCode === 200;\n'
    '      _fastApiLastCheck = Date.now();\n'
    '      resolve(_fastApiAvailable);\n'
    '    });\n'
    '    req.on("timeout", function() {\n'
    '      req.destroy();\n'
    '      _fastApiAvailable = false;\n'
    '      _fastApiLastCheck = Date.now();\n'
    '      resolve(false);\n'
    '    });\n'
    '    req.on("error", function() {\n'
    '      _fastApiAvailable = false;\n'
    '      _fastApiLastCheck = Date.now();\n'
    '      resolve(false);\n'
    '    });\n'
    '    req.end();\n'
    '  });\n'
    '}\n'
    '\n'
    'module.exports = {\n'
    '  callFastApiOCR: callFastApiOCR,\n'
    '  callFastApiExtractDates: callFastApiExtractDates,\n'
    '  isFastApiAvailable: isFastApiAvailable,\n'
    '  AI_SERVICE_URL: AI_SERVICE_URL\n'
    '};\n'
)

out = r'C:\Users\Zaid\Desktop\DockTrack-AI\server\src\services\ocr\FastApiOCRService.js'
with open(out, 'w', encoding='utf-8') as f:
    f.write(js_code)
print('Done. Wrote', len(js_code), 'bytes')
